### ISSUE TITLE
NoMethodError:  undefined method ... for "Audited::Audit":String

### ISSUE THREAD

**Issue by rocket-turtle** [collectiveidea/audited#647]
Hi there,

the changes from https://github.com/collectiveidea/audited/pull/609 introduced an breaking change.

```
2.7.6 :001 > Audited.audit_class.none
Traceback (most recent call last):
        1: from (irb):1
NoMethodError (undefined method `none' for "Audited::Audit":String)
```

It is easy to fix just change `Audited.audit_class` to `Audited.audit_model`.

```
2.7.6 :002 > Audited.audit_model.none
 => #<ActiveRecord::Relation []>
```

I just wane know if this is the way to go or are you planning to change it to the old behavior?

Others also noticed it: https://github.com/theforeman/foreman/pull/9568

@simmerz, @danielmorrison, @ekohl

Thank you all for your work
Jonas

**Comment by danielmorrison** [comment]
gah, I think we should do some work to make this a cleaner upgrade. Anyone want to tackle that? I don't have a lot of time this week, but can review PRs.

**Comment by rocket-turtle** [comment]
I gave it shot: https://github.com/collectiveidea/audited/pull/648/files

**Comment by DannyBen** [comment]
I believe I am encountering the same issue. 
Version 5.1 introduces a breaking change that is not documented as such, so I am not sure what is the needed change.

My code that works in 5.0.2:

```ruby
class Audit < Audited.audit_class
```

now generates `TypeError: superclass must be an instance of Class (given an instance of String)`

**Comment by danielmorrison** [comment]
Fixed in 5.2.0.
