### ISSUE TITLE
Bundler::GemRequireError with rails 5.2.0.rc1

### ISSUE THREAD

**Issue by pyromaniackeca** [collectiveidea/audited#422]
Hello,
I'm using audited 4.6.0 with ruby 2.5.0, after updating rails from 5.1.5 to 5.2.0.rc1, I'm getting this error while trying to run my specs:

```
Bundler::GemRequireError: There was an error while trying to load the gem 'audited'.
Gem Load Error is: undefined method `arity' for {:polymorphic=>true}:Hash
Backtrace for gem load error is:
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.rc1/lib/active_record/associations/builder/association.rb:51:in `build_scope'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.rc1/lib/active_record/associations/builder/association.rb:43:in `create_reflection'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.rc1/lib/active_record/associations/builder/association.rb:31:in `build'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.rc1/lib/active_record/associations.rb:1654:in `belongs_to'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/acts_as_paranoid-085b5cc6da14/lib/acts_as_paranoid/associations.rb:14:in `belongs_to_with_deleted'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/audited-4.6.0/lib/audited/audit.rb:37:in `<class:Audit>'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/audited-4.6.0/lib/audited/audit.rb:36:in `<module:Audited>'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/audited-4.6.0/lib/audited/audit.rb:3:in `<top (required)>'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:283:in `require'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:283:in `block in require'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:283:in `require'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/audited-4.6.0/lib/audited.rb:27:in `<top (required)>'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/home/nemanja/Documents/Development/qcontact/appserver/config/application.rb:18:in `<top (required)>'
/home/nemanja/Documents/Development/qcontact/appserver/config/environment.rb:2:in `require_relative'
/home/nemanja/Documents/Development/qcontact/appserver/config/environment.rb:2:in `<top (required)>'
/home/nemanja/Documents/Development/qcontact/appserver/spec/rails_helper.rb:5:in `require'
/home/nemanja/Documents/Development/qcontact/appserver/spec/rails_helper.rb:5:in `<top (required)>'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `require'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `block in requires='
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `each'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `requires='
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:111:in `each'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:21:in `configure'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:99:in `setup'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:86:in `run'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
/home/nemanja/.rbenv/versions/2.5.0/bin/rspec:23:in `load'
/home/nemanja/.rbenv/versions/2.5.0/bin/rspec:23:in `<top (required)>'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/home/nemanja/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/home/nemanja/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
/home/nemanja/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'
```

Could you please assist?

**Comment by tbrisker** [comment]
I think this is related to https://github.com/rails/rails/commit/9b53f74d897d346f44caae7b0cffcd900f986259#diff-a215bfc911ab0913d92695a0f20310ef - might actually be a bug in rails?

**Comment by pyromaniackeca** [comment]
That was my first thought as well, but I couldn't find any other people reporting it and it seems to me that such a bug would be noticed quickly. I will create an issue with them and see what they have to say about it.

**Comment by tbrisker** [comment]
@pyromaniackeca might be related to acts_as_paranoid as well. the audited line that triggers this is just a standard `belongs_to :auditable,  polymorphic: true`, nothing that should cause an error like this.

**Comment by pyromaniackeca** [comment]
Yeah I looked at the source, that's why I find it weird that if it was a rails bug it hasn't been discovered yet. Thanks for the `acts_as_paranoid` tip, I'll look into that.

**Comment by tbrisker** [comment]
Good luck, I'll close this issue for now since it doesn't seem to be related to audited, but feel free to reopen it if your investigation shows otherwise.

**Comment by pyromaniackeca** [comment]
Just to confirm if anyone else comes across this, the issue is indeed with `acts_as_paranoid`, removing the gem from the application allows the tests to run normally.

@tbrisker Thanks again for the help.
